# Generated by Django 2.2 on 2019-04-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneage_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%D'),
        ),
    ]
