# Generated by Django 2.2 on 2019-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneage_estimator', '0002_auto_20190412_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%D/'),
        ),
    ]
