# Generated by Django 2.2 on 2019-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneage_estimator', '0004_auto_20190412_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carpal_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='post',
            name='prediction',
            field=models.IntegerField(default=100),
        ),
    ]
